"""Bounded primary-paper reader with per-client system certificate trust."""
import asyncio
import re
import ssl
from urllib.parse import urljoin, urlparse

import httpx
import truststore

HOSTS = frozenset({"arxiv.org", "export.arxiv.org", "aclanthology.org",
                   "openaccess.thecvf.com", "proceedings.neurips.cc"})
MAX_BYTES = 12 * 1024 * 1024


async def search_papers(query):
    """Discover real arXiv records; identifiers are never generated by the LLM."""
    import xml.etree.ElementTree as ET
    context = truststore.SSLContext(ssl.PROTOCOL_TLS_CLIENT)
    async with httpx.AsyncClient(verify=context, timeout=25) as client:
        response = await client.get("https://export.arxiv.org/api/query", params={
            "search_query": query, "max_results": 5, "sortBy": "relevance"})
        response.raise_for_status()
    if len(response.content) > 1024 * 1024:
        raise ValueError("学术检索响应过大")
    root = ET.fromstring(response.content)
    ns = {"a": "http://www.w3.org/2005/Atom"}
    return [{"title": entry.findtext("a:title", "", ns).strip(),
             "url": entry.findtext("a:id", "", ns).replace("http://", "https://"),
             "abstract": entry.findtext("a:summary", "", ns)[:1800]}
            for entry in root.findall("a:entry", ns)]


def validate_url(url):
    parsed = urlparse(url)
    if (parsed.scheme != "https" or parsed.hostname not in HOSTS or
            parsed.username or parsed.password or parsed.port not in (None, 443)):
        raise ValueError("原文工具仅允许已登记学术站点的 HTTPS 地址")
    return url


def paper_url(url):
    validate_url(url)
    parsed = urlparse(url)
    if parsed.hostname in {"arxiv.org", "export.arxiv.org"}:
        match = re.fullmatch(r"/(?:abs|pdf)/(\d{4}\.\d{4,5}(?:v\d+)?)(?:\.pdf)?", parsed.path)
        if match:
            return "https://arxiv.org/pdf/" + match.group(1)
    return url


def extract_text(data, content_type):
    if data.startswith(b"%PDF"):
        import fitz
        with fitz.open(stream=data, filetype="pdf") as document:
            return "\n".join(f"[Page {i + 1}]\n{document[i].get_text()}"
                             for i in range(min(len(document), 30)))[:65000]
    if "html" not in content_type:
        raise ValueError("论文地址未返回 PDF 或 HTML")
    from bs4 import BeautifulSoup
    soup = BeautifulSoup(data, "html.parser")
    for node in soup(["script", "style", "nav", "footer"]):
        node.decompose()
    return soup.get_text("\n", strip=True)[:65000]


async def read_paper(url):
    return await asyncio.wait_for(_read_paper(url), timeout=60)


async def _read_paper(url):
    target = paper_url(url)
    context = truststore.SSLContext(ssl.PROTOCOL_TLS_CLIENT)
    async with httpx.AsyncClient(verify=context, timeout=25, follow_redirects=False) as client:
        for _ in range(4):
            validate_url(target)
            async with client.stream("GET", target) as response:
                if response.is_redirect:
                    target = urljoin(target, response.headers["location"])
                    validate_url(target)
                    continue
                response.raise_for_status()
                data = bytearray()
                async for chunk in response.aiter_bytes():
                    data.extend(chunk)
                    if len(data) > MAX_BYTES:
                        raise ValueError("论文下载超过 12 MiB 限制")
                text = await asyncio.to_thread(extract_text, bytes(data), response.headers.get("content-type", ""))
                if not text.strip():
                    raise ValueError("论文没有可提取文本，需 OCR 工具，未伪造内容")
                return {"url": target, "requested_url": url, "text": text,
                        "extraction_limit": "first 30 pages / 65000 characters"}
    raise ValueError("论文重定向次数超过限制")
