"""Bounded primary-paper reader with per-client system certificate trust."""
import asyncio
import re
import ssl
import os
import tempfile
import time
from email.utils import parsedate_to_datetime
from urllib.parse import urljoin, urlparse

import httpx
import truststore

HOSTS = frozenset({"arxiv.org", "export.arxiv.org", "aclanthology.org",
                   "openaccess.thecvf.com", "proceedings.neurips.cc"})
MAX_BYTES = int(os.getenv("REVIEW_PAPER_MAX_MIB", "64")) * 1024 * 1024
if not 1024 * 1024 <= MAX_BYTES <= 256 * 1024 * 1024:
    raise ValueError("REVIEW_PAPER_MAX_MIB must be between 1 and 256")


class ScholarlyRateLimit(RuntimeError):
    def __init__(self, seconds):
        self.seconds = seconds
        super().__init__(f"arXiv 检索限流（HTTP 429），需等待至少 {seconds:.0f} 秒后重试；更换关键词不能解除限流")


def retry_after_seconds(value, now=None):
    now = time.time() if now is None else now
    try:
        return max(1., float(value))
    except (ValueError, TypeError):
        try:
            return max(1., parsedate_to_datetime(value).timestamp() - now)
        except (ValueError, TypeError, AttributeError, OverflowError):
            return 60.


async def search_papers(query, *, start=0, max_results=15, sort_by="relevance"):
    """Discover real arXiv records; identifiers are never generated by the LLM."""
    import xml.etree.ElementTree as ET
    context = truststore.SSLContext(ssl.PROTOCOL_TLS_CLIENT)
    async with httpx.AsyncClient(verify=context, timeout=25) as client:
        response = await client.get("https://export.arxiv.org/api/query", params={
            "search_query": query, "start": start, "max_results": min(max_results, 30),
            "sortBy": sort_by, "sortOrder": "descending"})
        if response.status_code == 429:
            raise ScholarlyRateLimit(retry_after_seconds(response.headers.get("Retry-After")))
        response.raise_for_status()
    if len(response.content) > 1024 * 1024:
        raise ValueError("学术检索响应过大")
    root = ET.fromstring(response.content)
    ns = {"a": "http://www.w3.org/2005/Atom"}
    return [{"title": entry.findtext("a:title", "", ns).strip(),
             "url": entry.findtext("a:id", "", ns).replace("http://", "https://"),
             "published": entry.findtext("a:published", "", ns),
             "updated": entry.findtext("a:updated", "", ns),
             "abstract": entry.findtext("a:summary", "", ns)[:1800]}
            for entry in root.findall("a:entry", ns)]


def validate_url(url):
    parsed = urlparse(url)
    if (parsed.scheme != "https" or parsed.hostname not in HOSTS or
            parsed.username or parsed.password or parsed.port not in (None, 443)):
        raise ValueError("原文工具仅允许已登记学术站点的 HTTPS 地址")
    return url


def paper_url(url):
    validate_url(url)
    parsed = urlparse(url)
    if parsed.hostname in {"arxiv.org", "export.arxiv.org"}:
        match = re.fullmatch(r"/(?:abs|pdf)/(\d{4}\.\d{4,5}(?:v\d+)?)(?:\.pdf)?", parsed.path)
        if match:
            return "https://arxiv.org/pdf/" + match.group(1)
    return url


def extract_text(data, content_type):
    if data.startswith(b"%PDF"):
        import fitz
        with fitz.open(stream=data, filetype="pdf") as document:
            return "\n".join(f"[Page {i + 1}]\n{document[i].get_text()}"
                             for i in range(min(len(document), 30)))[:65000]
    if "html" not in content_type:
        raise ValueError("论文地址未返回 PDF 或 HTML")
    from bs4 import BeautifulSoup
    soup = BeautifulSoup(data, "html.parser")
    for node in soup(["script", "style", "nav", "footer"]):
        node.decompose()
    return soup.get_text("\n", strip=True)[:65000]


async def read_paper(url, *, consume_bytes=None):
    return await asyncio.wait_for(_read_paper(url, consume_bytes=consume_bytes), timeout=180)


async def _read_paper(url, *, consume_bytes=None):
    target = paper_url(url)
    context = truststore.SSLContext(ssl.PROTOCOL_TLS_CLIENT)
    async with httpx.AsyncClient(verify=context, timeout=25, follow_redirects=False) as client:
        for _ in range(4):
            validate_url(target)
            async with client.stream("GET", target) as response:
                if response.is_redirect:
                    target = urljoin(target, response.headers["location"])
                    validate_url(target)
                    continue
                response.raise_for_status()
                # Stream to disk rather than accumulating a PDF in RAM. The
                # temporary file is closed/deleted on errors and cancellation.
                with tempfile.NamedTemporaryFile(suffix=".paper") as downloaded:
                    size = 0
                    async for chunk in response.aiter_bytes(65536):
                        size += len(chunk)
                        if consume_bytes:
                            consume_bytes(len(chunk))
                        if size > MAX_BYTES:
                            raise ValueError(f"单篇文件超过 {MAX_BYTES // 1048576} MiB：{target}；可调整 REVIEW_PAPER_MAX_MIB")
                        downloaded.write(chunk)
                    downloaded.flush()
                    text, pages = await asyncio.to_thread(extract_file, downloaded.name,
                                                          response.headers.get("content-type", ""))
                if not text.strip():
                    raise ValueError("论文没有可提取文本，需 OCR 工具，未伪造内容")
                return {"url": target, "requested_url": url, "text": text,
                        "pages": pages, "bytes": size, "extraction_limit": None}
    raise ValueError("论文重定向次数超过限制")


def extract_file(path, content_type):
    import fitz
    with open(path, "rb") as source:
        is_pdf = source.read(4) == b"%PDF"
    if is_pdf:
        with fitz.open(path) as document:
            if len(document) > 1500:
                raise ValueError("论文超过 1500 页，需明确扩大解析预算")
            pages = [{"page": i + 1, "text": page.get_text()} for i, page in enumerate(document)]
        if sum(len(p["text"]) for p in pages) > 5_000_000:
            raise ValueError("全文文本超过 500 万字符，需扩大索引预算")
        return "\n".join(f'[Page {p["page"]}]\n{p["text"]}' for p in pages), pages
    with open(path, "rb") as source:
        if "html" not in content_type:
            raise ValueError("论文地址未返回 PDF 或 HTML")
        from bs4 import BeautifulSoup
        soup = BeautifulSoup(source.read(), "html.parser")
        for node in soup(["script", "style", "nav", "footer"]):
            node.decompose()
        text = soup.get_text("\n", strip=True)
        if len(text) > 5_000_000:
            raise ValueError("全文文本超过 500 万字符，需扩大索引预算")
    return text, [{"page": 1, "text": text}]
