"""Offline diagnostics for saved research runs, not a semantic quality scorer.

Example: python scripts/audit-research-run.py outputs/review_<id>
Add --acceptance outputs/acceptance_<id> for recorded usage and download checks.
No network, model calls, edits to historical artifacts, or inferred token usage.
"""
import argparse
from collections import Counter, defaultdict
import json
from pathlib import Path
import re


def source_key(url):
    match = re.fullmatch(r"https?://(?:export\.)?arxiv\.org/(?:abs|pdf|html)/(\d{4}\.\d{4,5})(?:v\d+)?(?:\.pdf)?/?", url)
    return "https://arxiv.org/abs/" + match[1] if match else url.rstrip("/")


def links(text):
    return {source_key(url.rstrip(".,;:")) for url in re.findall(r'https?://[^\s<>\[\]()"，。；]+', text)}


def audit(folder, acceptance=None):
    def read(name, default):
        path = folder / name
        return json.loads(path.read_text()) if path.exists() else default

    report_path = folder / "report-with-citations.md"
    report = report_path.read_text() if report_path.exists() else ""
    # Scope: URL-linked Markdown generated by this runtime. Numeric-only or
    # author-year citations without URLs require independent/manual resolution.
    body = re.split(r"(?im)^#{1,6}\s*(?:参考文献|参考资料|references|bibliography)\s*$", report)[0]
    body_links = links(body)
    paper_links = sorted(url for url in body_links if url.startswith("https://arxiv.org/abs/"))
    events_path = folder / "events.jsonl"
    events = [json.loads(line) for line in events_path.read_text().splitlines() if line.strip()] if events_path.exists() else []
    reads = defaultdict(list)
    for event in events:
        result = event.get("result")
        if event.get("tool") == "read_passage" and event.get("status") == "completed" and isinstance(result, dict):
            key = (source_key(result["source"]), result.get("page"), result.get("offset"))
            reads[key].append(event.get("agent"))
    children = []
    for path in sorted(folder.glob("subagent-*.json")):
        record = json.loads(path.read_text())
        result = record.get("result", {})
        children.append({"artifact": path.name, "assignment": record.get("assignment", {}),
                         "timing": record.get("timing"), "status": result.get("status"),
                         "findings_count": len(result.get("findings", [])), "gaps": result.get("gaps", [])})
    recorded = {}
    if acceptance and (acceptance / "result.json").exists():
        recorded = json.loads((acceptance / "result.json").read_text())
    calls = sum(map(len, reads.values()))
    return {
        "schema_version": 1, "review_directory": str(folder), "report_exists": report_path.exists(),
        "run_metadata": read("run.json", {}),
        "body_length_units": len(re.findall(r"[\u4e00-\u9fff]|[A-Za-z0-9]+", re.sub(r"https?://\S+", "", body))),
        "body_linked_sources": sorted(body_links), "body_linked_arxiv_papers": paper_links,
        "body_linked_arxiv_count": len(paper_links),
        "bibliography_only_links": sorted(links(report) - body_links),
        "direct_read_calls": calls, "distinct_direct_passages": len(reads),
        "repeated_direct_reads": calls - len(reads),
        "shared_passages": [{"source": key[0], "page": key[1], "offset": key[2],
                             "calls": len(agents), "agents": sorted(set(agents))}
                            for key, agents in reads.items() if len(agents) > 1],
        "tool_failure_counts": dict(Counter(event.get("tool") for event in events if event.get("status") == "failed")),
        "children": children, "citation_review": read("citation-review.json", {}),
        "recorded_usage": recorded.get("usage"), "recorded_timing": recorded.get("timing"),
        "limitations": ["URL counts are not citation correctness or semantic coverage.",
                        "arXiv count excludes other publishers and deduplicates versions; inspect those separately.",
                        "Repeated passage reads are not automatically wasted work or repeated downloads.",
                        "Body length is an approximate observation, never a pass/fail threshold.",
                        "Provider token usage may include cache hits; no currency cost is inferred."],
    }


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("review", type=Path)
    parser.add_argument("--acceptance", type=Path)
    args = parser.parse_args()
    if not args.review.is_dir():
        parser.error("review must be an existing saved-run directory")
    print(json.dumps(audit(args.review, args.acceptance), ensure_ascii=False, indent=2))
